import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <div className="flex ">
          <div className=""><Sidebar/></div>
          <div className="w-[calc(100vw-340px)]">{children}</div>
        </div>
      </body>
    </html>
  );
}
